--- #YAML:1.0
name:                Memoize-Expire-ByInstance
version:             0.500001
abstract:            A Memoize plugin which provides per-class-instance expiration of memoized data.
license:             perl
author:              
    - Jamie Beverly <jbeverly@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Scalar::Util:                  1.1
    Test::Class:                   0.3
    Test::More:                    0
    Time::HiRes:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
