--- #YAML:1.0
name:               Memoize-Expire-ByInstance
version:            0.5
abstract:           A Memoize plugin which provides per-class-instance expiration of memoized data.
author:
    - Jamie Beverly <jbeverly@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Scalar::Util:  1.2
    Test::Class:   0.3
    Test::More:    0
    Time::HiRes:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
